In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [ ]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
tokens= word_tokenize(document)

In [ ]:
tokens


['About',
 'the',
 'Program',
 'What',
 'is',
 'the',
 'course',
 'fee',
 'for',
 'Data',
 'Science',
 'Mentorship',
 'Program',
 '(',
 'DSMP',
 '2023',
 ')',
 'The',
 'course',
 'follows',
 'a',
 'monthly',
 'subscription',
 'model',
 'where',
 'you',
 'have',
 'to',
 'make',
 'monthly',
 'payments',
 'of',
 'Rs',
 '799/month',
 '.',
 'What',
 'is',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 '?',
 'The',
 'total',
 'duration',
 'of',
 'the',
 'course',
 'is',
 '7',
 'months',
 '.',
 'So',
 'the',
 'total',
 'course',
 'fee',
 'becomes',
 '799',
 '*',
 '7',
 '=',
 'Rs',
 '5600',
 '(',
 'approx',
 '.',
 ')',
 'What',
 'is',
 'the',
 'syllabus',
 'of',
 'the',
 'mentorship',
 'program',
 '?',
 'We',
 'will',
 'be',
 'covering',
 'the',
 'following',
 'modules',
 ':',
 'Python',
 'Fundamentals',
 'Python',
 'libraries',
 'for',
 'Data',
 'Science',
 'Data',
 'Analysis',
 'SQL',
 'for',
 'Data',
 'Science',
 'Maths',
 'for',
 'Machine',
 'Learning',
 'ML',
 'Algorithms',
 'P

In [ ]:
vocab={"<UNK>":0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]= len(vocab)

In [ ]:
len(vocab)

311

In [ ]:
len(document.split("\n")) #split  after evry line break

78

In [ ]:
input_sentence= document.split("\n")

In [ ]:
def text_to_indicies(sentence,vocab):
  indicies_sentence=[]
  for token in sentence:
    if token in vocab:
      indicies_sentence.append(vocab[token])
    else:
      indicies_sentence.append(vocab["<UNK>"])
  return indicies_sentence


In [ ]:

numerical_sentence=[]

for sentence in input_sentence:
  sentence_indicies= text_to_indicies(word_tokenize(sentence),vocab)
  numerical_sentence.append(sentence_indicies)

In [ ]:
numerical_sentence

[[1, 2, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [16, 6, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 19, 27, 28, 29, 30, 31],
 [4, 5, 2, 32, 33, 28, 2, 6, 34],
 [16,
  32,
  33,
  28,
  2,
  6,
  5,
  35,
  36,
  31,
  37,
  2,
  32,
  6,
  7,
  38,
  39,
  40,
  35,
  41,
  29,
  42,
  12,
  43,
  31,
  15],
 [4, 5, 2, 44, 28, 2, 45, 46, 34],
 [47, 48, 49, 50, 2, 51, 52, 53],
 [54, 55],
 [54, 56, 8, 9, 10],
 [9, 57],
 [58, 8, 9, 10],
 [59, 8, 60, 61],
 [62, 63],
 [64, 62],
 [65],
 [66, 67],
 [68, 69, 70, 2, 71, 44, 72, 73, 74, 53, 75],
 [76, 77, 61, 78, 79, 49, 18, 80, 28, 81, 46, 34],
 [82, 83, 79, 78, 77, 61, 84, 85, 86, 18, 80, 28, 81, 46, 87, 88, 89, 31],
 [4, 90, 91, 92, 18, 93, 94, 34, 76, 91, 95, 18, 96, 28, 2, 94, 34],
 [97,
  98,
  99,
  100,
  85,
  101,
  83,
  102,
  103,
  90,
  23,
  92,
  18,
  94,
  23,
  69,
  104,
  105,
  78,
  106,
  2,
  96,
  31],
 [107, 69, 91, 108, 2, 109, 110, 34],
 [111,
  81,
  112,
  113,
  25,
  114,
  115,
  116,
  115,
  117,


In [ ]:
training_sequence=[]
for sentence in numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append((sentence[:i+1]))

In [ ]:
len(training_sequence)

944

In [ ]:

length=[]

for sequence in training_sequence:
  length.append(len(sequence))
max(length)



63

In [ ]:
#padding

paddeded_sequence=[]
for sequence in training_sequence:
  paddeded_sequence.append(([0]*(max(length)-len(sequence))+sequence))

len(paddeded_sequence[0])

63

In [ ]:
torch_padded_Sequence= torch.tensor(paddeded_sequence)

In [ ]:
torch_padded_Sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 307, 190, 308],
        [  0,   0,   0,  ..., 190, 308, 309],
        [  0,   0,   0,  ..., 308, 309, 310]])

In [ ]:
X=torch_padded_Sequence[:,:-1]
Y=torch_padded_Sequence[:,-1]

In [ ]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
Y[0]

tensor(2)

In [ ]:
class CoustomDataset(Dataset):

  def __init__(self,X,Y):
    self.x=X
    self.y=Y

  def __len__(self):
    return self.x.shape[0]

  def __getitem__(self,index):
    return self.x[index], self.y[index]


In [ ]:
dataset=CoustomDataset(X,Y)

In [ ]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [ ]:
dataloader=DataLoader(dataset, batch_size=32, shuffle=True)

In [ ]:
len(vocab)

311

In [ ]:
class LstmModel(nn.Module):

  def __init__(self,vocab_size):
    super().__init__()

    self.embeded= nn.Embedding(vocab_size,100)  #100 is embeded dimension each word will be of 100 dimensions
    self.lstm= nn.LSTM(100,150, batch_first=True)
    self.fc= nn.Linear(150,vocab_size) #will give probablity correspond to every word

  def forward(self,x):
    embedded_x= self.embeded(x)
    intermediate_hidden_state,(final_hidden_state, final_cell_state)= self.lstm(embedded_x) #returns 3 things
    output=self.fc(final_hidden_state.squeeze(0))
    return output

In [ ]:
model= LstmModel(len(vocab))

In [ ]:
device= torch.device("cuda")

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
model.to(device)

LstmModel(
  (embeded): Embedding(311, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=311, bias=True)
)

In [ ]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
#training loop

for epoch in range(epochs):
  total_loss=0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output.squeeze(), batch_y)

    loss.backward()

    total_loss=total_loss+loss.item()

    optimizer.step()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")





Epoch: 1, Loss: 166.7646
Epoch: 2, Loss: 148.2803
Epoch: 3, Loss: 137.0428
Epoch: 4, Loss: 125.5136
Epoch: 5, Loss: 113.7579
Epoch: 6, Loss: 102.1551
Epoch: 7, Loss: 91.3606
Epoch: 8, Loss: 81.3570
Epoch: 9, Loss: 72.1532
Epoch: 10, Loss: 64.2820
Epoch: 11, Loss: 56.6528
Epoch: 12, Loss: 50.0786
Epoch: 13, Loss: 43.8611
Epoch: 14, Loss: 38.4185
Epoch: 15, Loss: 33.6711
Epoch: 16, Loss: 29.7625
Epoch: 17, Loss: 26.3901
Epoch: 18, Loss: 23.5295
Epoch: 19, Loss: 20.9182
Epoch: 20, Loss: 18.6094
Epoch: 21, Loss: 16.8713
Epoch: 22, Loss: 15.0920
Epoch: 23, Loss: 13.7785
Epoch: 24, Loss: 12.5620
Epoch: 25, Loss: 11.5766
Epoch: 26, Loss: 10.6279
Epoch: 27, Loss: 9.8482
Epoch: 28, Loss: 9.4632
Epoch: 29, Loss: 8.6987
Epoch: 30, Loss: 8.1575
Epoch: 31, Loss: 7.7324
Epoch: 32, Loss: 7.3004
Epoch: 33, Loss: 6.9886
Epoch: 34, Loss: 6.9236
Epoch: 35, Loss: 6.4932
Epoch: 36, Loss: 6.1686
Epoch: 37, Loss: 5.9353
Epoch: 38, Loss: 5.7866
Epoch: 39, Loss: 5.6141
Epoch: 40, Loss: 5.4742
Epoch: 41, Loss: 

In [ ]:
def prediction(model,sentence,vocab):
  numerical_sentence= text_to_indicies(word_tokenize(sentence),vocab)

  #padding

  padded_text= torch.tensor([0]*(max(length)-len(numerical_sentence))+numerical_sentence,dtype=torch.long)

  output=model(padded_text.unsqueeze(0))

  value,index= torch.max(output, dim=1)

  return sentence+ " " + list(vocab.keys())[index.item()]

In [ ]:
prediction(model,"Yes, just select past week doubt ", vocab)

'Yes, just select past week doubt  in'

In [ ]:
input_text="Yes, just select past week doubt "

import time

num_tokens=10

for i in range(num_tokens):
  output_text= prediction(model,input_text,vocab)

  print(output_text)

  time.sleep(1)

  input_text=output_text

Yes, just select past week doubt  in
Yes, just select past week doubt  in the
Yes, just select past week doubt  in the doubt
Yes, just select past week doubt  in the doubt clearance
Yes, just select past week doubt  in the doubt clearance google
Yes, just select past week doubt  in the doubt clearance google form
Yes, just select past week doubt  in the doubt clearance google form .
Yes, just select past week doubt  in the doubt clearance google form . .
Yes, just select past week doubt  in the doubt clearance google form . . Here
Yes, just select past week doubt  in the doubt clearance google form . . Here is


In [ ]:
# Function to calculate accuracy
def calculate_accuracy(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # No need to compute gradients
        for batch_x, batch_y in dataloader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            # Get model predictions
            outputs = model(batch_x)

            # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)

            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

# Compute accuracy
accuracy = calculate_accuracy(model, dataloader, device)
print(f"Model Accuracy: {accuracy:.2f}%")

NameError: name 'dataloader1' is not defined